### ISSUE TITLE
Heading should handle the situation when selection is in the unknown block

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-headings#32]
Now heading crash when the selection is in the block which is not listed here: https://github.com/ckeditor/ckeditor5-headings/blob/2003c9b1de31f5475624681f097819110f5a45ad/src/headingsengine.js#L12-L17 

That is because of this line: https://github.com/ckeditor/ckeditor5-headings/blob/2003c9b1de31f5475624681f097819110f5a45ad/src/headingscommand.js#L51

`this.value` is an observable and fires event. If `format` is `undefined` it causes bug here:
https://github.com/ckeditor/ckeditor5-headings/blob/2003c9b1de31f5475624681f097819110f5a45ad/src/headings.js#L63

I believe that heading should handle the situation when the format is unknown. The final solution should be not to show any format in the dropdown menu or show the default (paragraph?).

The more tricky question is what should happen when user change the option there? Should the current block be removed and replace by the header? I do not think so. I think that header should be inserted inside that block, if it is allowed.

**Comment by Reinmar** [comment]
@scofalik has fixed this. The PR is already on master. Value of the command defaults to the default block if you are not in a known block.

This is a reasonable behaviour I think, though, not a perfect one. If anyone knows what should be displayed in the dropdown (it's mainly about the button title, cause in the drop down list you can have the usual options – but none of them selected) then please let us know :D.

**Comment by Reinmar** [comment]
@pjasiun please confirm that it's already fixed and close if you think that this is enough for now.

**Comment by pjasiun** [comment]
Yep, it works now, great job. Can we remove this TODO (https://github.com/ckeditor/ckeditor5-headings/blob/2003c9b1de31f5475624681f097819110f5a45ad/src/headingscommand.js#L50) now?

**Comment by Reinmar** [comment]
> Can we remove this TODO (https://github.com/ckeditor/ckeditor5-headings/blob/2003c9b1de31f5475624681f097819110f5a45ad/src/headingscommand.js#L50) now?

-> @scofalik and @szymonkups  :)
