### ISSUE TITLE
What should be the command and button name?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-headings#6]
It's `format` currently, but the package is called `formats`... It may be confusing.

**Comment by Reinmar** [comment]
We decided to rename this whole package to `ckeditor5-heading` and all classes inside to singular too. This is one heading feature with different "level" value.

**Comment by Reinmar** [comment]
There were some doubts in https://github.com/ckeditor/ckeditor5-headings/issues/33#issuecomment-248572654 whether we should rename the package.

I've been for plural at the beginning, but it's actually a single feature. Just like the link feature allows to create various links, in the same way, the heading feature allows creating various headings.

So why is it `basic-style*s*`? Because there are multiple different and independent features there.

Does it make sense still?

**Comment by Reinmar** [comment]
And what about command and feature names? Please check the current naming of classes and items (like the button).

**Comment by fredck** [comment]
Damn yes.. then `heading`... so if you want to align this, go ahead with `heading` everywhere

**Comment by Reinmar** [comment]
It's so 50:50 between those names that every time you make a decision you give me a different answer :D I can torture you infinitely :D.

**Comment by Reinmar** [comment]
But I took https://github.com/ckeditor/ckeditor5-headings/issues/6#issuecomment-248585580 from your words actually (seriously :P) so I'd go with it, cause it started to make sense for me (initially I was for "headings" :D).

**Comment by Reinmar** [comment]
Heh, while working on this I realised how this actually should be done.

* The dropdown must be called `headings`. It applies multiple headings.
* The command must be called `HeadingCommand` and should be refactored to only apply a single heading style. It should be registered in editor for each configured format as `heading1`, heading2`, etc. This will allow making "H1", "H2" buttons easily.
* The feature may be called `headings` then because it has multiple heading commands.

And I wanted to press "Submit" only to realise that none of this is "must", just "may". Maybe except the first point, because it really sounds wrong if the dropdown is called `heading`. But you can easily create buttons anyway (you just need to define their `isOn` state as `cmd.value == expectedFormat`). And one command is better than multiple commands because it's easier to document.

Then I realised that:

```js
editor.execute( 'headings', 'heading1' );
```

looks weird. After all, you're applying just one heading. Just like you're creating one list with `list` command (if type is a of that command value).

I need to slip on that, cause this is getting ridiculous :D. But right now I'm for:

* heading feature (because list feature)
* headings dropdown (because there are multiple level of headings you can apply with it)
* heading command (because it apply one heading)

Note: this is really very similar to the list case. In both cases the level (of a heading) / type (of a list) is just an attribute – variation of the "feature". The only difference here is that if list feature will expose two buttons – "numbered list" and "ordered list", while heading feature "headings" dropdown.

**Comment by Reinmar** [comment]
OK, 17 hours later and the things I wrote above still make sense for me.

1. It should be `heading` feature (because it's `list` feature).
2. There should be either multiple commands – each for a different heading or one command but still called `heading`.
3. There should be `headings` dropdown as it covers multiple levels.

RFC.

**Comment by Reinmar** [comment]
Changed in #35.
