### ISSUE TITLE
Selection issues

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-headings#7]
TC1:

0. Open http://tests.ckeditor.dev:1030/build/amd/tests/formats/manual/formats
1. Put selection somewhere in the editor.
2. Open the dropdown and click one of the options.

Expected: The format in the editor should change and you should see a blinking caret inside (at the position where you placed it).

**Comment by Reinmar** [comment]
Ok, a simple fix is to focus the editable after an item in the dropdown was clicked. This works in most cases. It fails when inside a dropdown you cause some selectionchange events by dragging the items. Apparently, selectionchange event breaks selection in the view, even though the view was blurred.

cc @pjasiun

**Comment by Reinmar** [comment]
Actually, it's even a reasonable to focus the editor in `itemListModel#execute` listener. This is UI related behaviour which we can code in such a place... however, I don't know how to edit the editor, because I don't know which editable I should focus. So this may require some method in the engine.

**Comment by Reinmar** [comment]
I reported 3 issues that needs to be checked and or fixed in order to resolve this issue:

* https://github.com/ckeditor/ckeditor5-engine/issues/488
* https://github.com/ckeditor/ckeditor5-engine/issues/489
* https://github.com/ckeditor/ckeditor5-engine/issues/490

**Comment by pjasiun** [comment]
And I reported one more: https://github.com/ckeditor/ckeditor5-engine/issues/491

**Comment by Reinmar** [comment]
There is an important followup: https://github.com/ckeditor/ckeditor5-engine/issues/490. It's so easy to trigger this bug that I'm considering fixing it in 0.1.0 still.
