### ISSUE TITLE
Rename the feature to "heading"

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5-headings#8]
I think that the name "formats" is a dirty inheritance from CKEditor 4. IMHO this features should be called "Heading" and should be specialized on headings only.

**Comment by Reinmar** [comment]
Makes sense. I've been thinking about this feature as about something what could accommodate all possible formats like also blockquote or... sth :D. That's been requested in the past, that there's a single place with all of them, but you made me realise that this doesn't need to be a single package. If anyone wants such a combo he/she will have to use the headings package plus some other formatting features and combine them in one dropdown (so it's more about configuring the toolbar).

**Comment by Reinmar** [comment]
BTW. shouldn't it be `ckeditor5-headings`? We've got `basic-styles`.

**Comment by fredck** [comment]
Yes, "headings" my sound better.

**Comment by Reinmar** [comment]
In a followup we decided to change the name.
